In [1]:
from cme.diffusion_models import diffusion_loop_method as dd
import cme.utils.common_logging as cl
import numpy as np
from cme.utils import common_utils as ut
import pandas as pd
import os
import pymc as pm
from pytensor import tensor as at

In [2]:
(0.2515518 + 2*0.0008319) * np.exp( ((0.2515518 + 2*0.0008319)**2) / (2*0.0008319) )

1.3802884675754678e+16

In [3]:
lp_v, v, a, z, t_er,  X, RT = dd._test_likelihood_using_prior(100, 20)
v = 1.5
a = 2
z = 0.5
t_er = 0.55

2023-05-09 08:33:41,518 - diffusion - DEBUG - Starting Diffusion test
2023-05-09 08:34:02,171 - diffusion - DEBUG - lp: 10.214677564249476
2023-05-09 08:34:02,183 - diffusion - DEBUG - X:[[0 0 0 ... 0 1 0]
 [0 0 1 ... 1 0 1]
 [1 1 0 ... 1 1 1]
 ...
 [0 0 1 ... 1 1 0]
 [0 1 1 ... 0 1 1]
 [0 1 0 ... 0 0 1]]
2023-05-09 08:34:02,194 - diffusion - DEBUG - RT:[[3.24212765 3.37628285 3.07504872 ... 2.46830202 2.14244028 3.36785562]
 [1.1789526  1.12805195 1.93997498 ... 1.07833416 1.35204186 1.46021263]
 [0.7885196  1.40598381 3.68022266 ... 0.52469673 2.6128984  3.48054646]
 ...
 [0.04273256 0.79717111 3.66961506 ... 0.4234925  0.56842232 3.25714363]
 [3.59048004 1.22394292 1.61873835 ... 3.61445202 0.28462137 2.39784825]
 [0.20924435 0.77640637 3.42425262 ... 0.7426118  2.7576066  2.8697041 ]]
2023-05-09 08:34:02,194 - diffusion - INFO - Test Successful!


In [4]:
lp_v = [dd._test_likelihood_using_prior(100, 20)[0] for i in range(100)]


2023-05-09 08:34:02,414 - diffusion - DEBUG - Starting Diffusion test
2023-05-09 08:34:03,728 - diffusion - DEBUG - lp: 10.891833035393653
2023-05-09 08:34:03,739 - diffusion - DEBUG - X:[[1 0 1 ... 1 0 0]
 [1 0 1 ... 0 0 0]
 [0 0 1 ... 1 1 0]
 ...
 [1 0 1 ... 1 0 0]
 [0 1 1 ... 1 0 1]
 [0 0 0 ... 1 0 0]]
2023-05-09 08:34:03,751 - diffusion - DEBUG - RT:[[0.10086945 1.31294807 3.46230309 ... 2.59730424 0.4571467  0.85367771]
 [3.58082589 2.07178344 0.56981696 ... 2.06975863 3.18170687 3.27597878]
 [0.40405073 0.55185049 3.437124   ... 1.11835007 3.94050445 0.29180831]
 ...
 [2.8493879  0.41822369 3.55671518 ... 2.50288364 2.90377964 2.36248033]
 [2.74854675 1.07748604 1.3483225  ... 2.44190563 2.11270499 2.61968634]
 [2.38831305 0.2023652  0.59058464 ... 1.20966054 1.24721744 1.00119287]]
2023-05-09 08:34:03,752 - diffusion - INFO - Test Successful!
2023-05-09 08:34:03,900 - diffusion - DEBUG - Starting Diffusion test
2023-05-09 08:34:04,954 - diffusion - DEBUG - lp: 9.772793427489937


In [5]:
lp_v

[array(10.89183304),
 array(9.77279343),
 array(10.09965838),
 array(9.61176712),
 array(5.55297526),
 array(10.29903556),
 array(10.82363024),
 array(10.05763996),
 array(9.14022066),
 array(10.05433151),
 array(10.44076158),
 array(11.48628695),
 array(10.17738553),
 array(9.72943916),
 array(9.81396253),
 array(9.93778082),
 array(10.08816748),
 array(11.21932711),
 array(9.62644608),
 array(10.46782073),
 array(9.26097682),
 array(9.86781127),
 array(9.20019682),
 array(10.47819855),
 array(10.87007872),
 array(8.71639073),
 array(9.84759976),
 array(7.82127302),
 array(9.8046143),
 array(10.90264714),
 array(9.82287386),
 array(10.29429271),
 array(10.10183578),
 array(11.65559936),
 array(11.49699814),
 array(10.5704837),
 array(12.67967588),
 array(9.01700296),
 array(9.37900439),
 array(10.56644832),
 array(10.28998096),
 array(9.48162508),
 array(10.21024078),
 array(13.67256979),
 array(10.36164129),
 array(10.47092591),
 array(10.5248748),
 array(10.64178859),
 array(7.75322

In [6]:
RT.mean(axis=1).shape

(100,)

In [7]:
df = pd.DataFrame({"lp":lp_v.flatten(), "RT":RT.mean(axis=1).flatten()})
df

AttributeError: 'list' object has no attribute 'flatten'

In [ ]:
df.plot(x="RT", y="lp", kind="scatter")

In [ ]:
df.loc[:,"lp"].plot(kind="box")

In [ ]:
np.save("v.npy",v)
np.save("a.npy",a)
np.save("z.npy",z)
np.save("t_er.npy",t_er)
np.save("X.npy",X)
np.save("RT.npy",RT)

In [ ]:
#prior_chain = dd.sample_prior_data(10,2,9)

In [ ]:
#post_chain = dd.sample_posterior_params(RT, X, 10,2,10)
