In [1]:
from cme.diffusion_models import diffusion_loop_method as dd
import cme.utils.common_logging as cl
import numpy as np
from cme.utils import common_utils as ut
import pandas as pd
import os
import pymc as pm
from pytensor import tensor as at

In [2]:
(0.2515518 + 2*0.0008319) * np.exp( ((0.2515518 + 2*0.0008319)**2) / (2*0.0008319) )

1.3802884675754678e+16

In [3]:
lp_v, v, a, z, t_er,  X, RT = dd._test_likelihood_using_prior(100, 20)
v = 1.5
a = 2
z = 0.5
t_er = 0.55

2023-05-10 15:58:51,557 - diffusion - DEBUG - Starting Diffusion test
2023-05-10 15:59:10,282 - diffusion - DEBUG - lp: 57.61107439708661
2023-05-10 15:59:10,297 - diffusion - DEBUG - X:[[0 1 1 ... 1 0 0]
 [0 0 0 ... 1 0 1]
 [0 1 1 ... 0 1 0]
 ...
 [0 0 0 ... 0 1 0]
 [1 1 0 ... 1 1 1]
 [1 0 1 ... 0 1 0]]
2023-05-10 15:59:10,311 - diffusion - DEBUG - RT:[[2.50241869 0.2393833  3.45773251 ... 2.74492633 3.11249158 3.07718505]
 [3.92239906 2.52214989 1.43969627 ... 2.66764829 1.14087938 3.91517793]
 [0.06640959 1.63294172 2.82536872 ... 3.17230615 2.37808791 3.08813678]
 ...
 [0.02387357 2.8776865  1.53722864 ... 3.98812296 0.54962145 3.98014458]
 [0.06320975 0.60309786 1.1390848  ... 3.48911288 3.34092669 3.40436245]
 [1.64304956 2.12697887 3.20631998 ... 3.51728855 1.74387156 1.58610631]]
2023-05-10 15:59:10,311 - diffusion - INFO - Test Successful!


In [4]:
lp_v = [dd._test_likelihood_using_prior(100, 20)[0] for i in range(100)]


2023-05-10 15:59:10,524 - diffusion - DEBUG - Starting Diffusion test
2023-05-10 15:59:12,008 - diffusion - DEBUG - lp: 626.0450896049747
2023-05-10 15:59:12,023 - diffusion - DEBUG - X:[[0 0 1 ... 1 1 0]
 [0 0 1 ... 1 0 0]
 [0 1 1 ... 1 0 0]
 ...
 [1 0 0 ... 0 0 1]
 [1 1 1 ... 0 1 1]
 [1 1 1 ... 0 0 1]]
2023-05-10 15:59:12,039 - diffusion - DEBUG - RT:[[0.25013166 1.23787067 2.43800472 ... 0.01112238 2.41070028 2.83172528]
 [3.98832761 0.16636015 3.69888065 ... 1.06192863 3.17671143 0.31277894]
 [3.69614468 1.09447232 3.04085859 ... 3.21499302 0.19284218 3.89563583]
 ...
 [3.68647972 3.33027382 2.24643638 ... 0.2841902  3.97964741 0.89854484]
 [0.64498198 1.17134469 0.53435442 ... 1.42521631 3.41794793 1.12040212]
 [2.7703627  1.35666539 2.01513797 ... 3.09929723 0.18805006 1.86954282]]
2023-05-10 15:59:12,039 - diffusion - INFO - Test Successful!
2023-05-10 15:59:12,175 - diffusion - DEBUG - Starting Diffusion test
2023-05-10 15:59:13,450 - diffusion - DEBUG - lp: 248.58779540449055


In [5]:
lp_v

[array(626.0450896),
 array(248.5877954),
 array(126.35763492),
 array(563.08501583),
 array(443.96475942),
 array(507.69438303),
 array(37.91071391),
 array(209.84358668),
 array(37.2583738),
 array(646.60131863),
 array(41.36478219),
 array(46.14243811),
 array(238.72453443),
 array(58.54194693),
 array(33.16121161),
 array(295.78024215),
 array(627.28332266),
 array(50.40143534),
 array(40.54297212),
 array(689.54677085),
 array(39.67917966),
 array(25.8796819),
 array(68.18148315),
 array(487.56094433),
 array(93.87709342),
 array(40.41588691),
 array(204.77234046),
 array(36.89442225),
 array(178.05204981),
 array(44.98012967),
 array(3.7460785),
 array(24.39414926),
 array(72.46632131),
 array(380.67094525),
 array(372.14005008),
 array(37.81559704),
 array(43.38463338),
 array(147.77315281),
 array(87.76568025),
 array(191.75663439),
 array(115.41371308),
 array(42.54931044),
 array(98.24139259),
 array(19.669715),
 array(9.20035186),
 array(573.21648061),
 array(406.83599921),


In [6]:
RT.mean(axis=1).shape

(100,)

In [7]:
df = pd.DataFrame({"lp":lp_v.flatten(), "RT":RT.mean(axis=1).flatten()})
df

AttributeError: 'list' object has no attribute 'flatten'

In [ ]:
df.plot(x="RT", y="lp", kind="scatter")

In [ ]:
df.loc[:,"lp"].plot(kind="box")

In [ ]:
np.save("v.npy",v)
np.save("a.npy",a)
np.save("z.npy",z)
np.save("t_er.npy",t_er)
np.save("X.npy",X)
np.save("RT.npy",RT)

In [ ]:
#prior_chain = dd.sample_prior_data(10,2,9)

In [ ]:
#post_chain = dd.sample_posterior_params(RT, X, 10,2,10)
