In [2]:
import cme.decision_models.confidence_accumulation as ca
import numpy as np
import scipy.stats as stats
import pandas as pd
import seaborn as sns

In [3]:
n_states, start_width, threshold, measurement_prob, delta, mu, sigma, I, J = 7, 3, 1, 1, 1, np.asarray([[2]]), np.asarray([[1]]), 1, 5
model_type = "Markov"

In [4]:
t_s = stats.uniform(0,20).rvs((I,J))
t_s

array([[ 3.62174559,  6.10125829,  4.87780171,  5.84856553, 10.716174  ]])

In [5]:
intensity_matrix = ca.get_intensity_matrix(n_states, mu, sigma, model_type=model_type)
phi_0 = ca._get_initial_state(n_states, start_width,model_type=model_type, prior_type="Centered")
intensity_matrix, phi_0

(Array([[[[-1. , -0.5,  0. ,  0. ,  0. ,  0. ,  0. ],
          [ 1. , -1. , -0.5,  0. ,  0. ,  0. ,  0. ],
          [ 0. ,  1.5, -1. , -0.5,  0. ,  0. ,  0. ],
          [ 0. ,  0. ,  1.5, -1. , -0.5,  0. ,  0. ],
          [ 0. ,  0. ,  0. ,  1.5, -1. , -0.5,  0. ],
          [ 0. ,  0. ,  0. ,  0. ,  1.5, -1. ,  1. ],
          [ 0. ,  0. ,  0. ,  0. ,  0. ,  1.5, -1. ]]]], dtype=float64),
 Array([[[[0.        ],
          [0.        ],
          [0.33333333],
          [0.33333333],
          [0.33333333],
          [0.        ],
          [0.        ]]]], dtype=float64))

In [6]:
Mc, Mw, Mn = ca._get_measurement_matrix(n_states, threshold, prob=measurement_prob, model_type = model_type)
Mc

Array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1.]], dtype=float64)

In [7]:
t = np.asarray([[4.5]]) #t_s #
phi_t = ca.perform_state_transition(intensity_matrix=intensity_matrix, RT_s=t, RA_s = None, delta=delta, 
Mc = Mc, Mn = Mn, Mw = Mw, phi_0=phi_0, 
transition_type="RT", likelihood_type="SINGLE")
phi_t.shape

(1, 1, 7, 1)

In [8]:
phi_t

Array([[[[-0.00147064],
         [ 0.00488687],
         [-0.01444839],
         [ 0.05333723],
         [-0.15088042],
         [ 0.44175533],
         [ 0.66682001]]]], dtype=float64)

In [ ]:
phi_t.sum(axis=-2, keepdims=True)

In [ ]:
[phi_i_j.squeeze().sum() for phi_i in phi_t for phi_i_j in phi_i ]

In [ ]:
phi_t[0,0,:,0]

In [ ]:
stats.multinomial(n=1, p=phi_t[0,0,:,0]).rvs()

In [ ]:
[stats.multinomial(n=1, p=phi_i_j.squeeze()).rvs() for phi_i in phi_t for phi_i_j in phi_i ]