In [1]:
import cme.decision_models.confidence_accumulation as ca
import numpy as np
import scipy.stats as stats
import pandas as pd
import seaborn as sns
import numpyro as npy
import numpyro.distributions as dist

In [2]:
max_samples, max_RT = 400, 40

In [3]:
n_states, start_width, delta, measurement_prob,  = 101, 11, 0.5, 0.8
I, J = 20, 100

In [4]:
threshold, measurement_prob, mu, sigma = 1, 1, np.asarray([[1]]), np.asarray([[2]])
model_type = "Markov"
transition_type="RT"

In [5]:
t_s = stats.uniform(delta,max_RT/delta).rvs((I,max_samples))
t_s.shape

(20, 400)

In [6]:
t_s

array([[18.26580445,  1.12335004, 67.21563574, ..., 60.68577252,
        79.68778353, 31.95390927],
       [46.48124839, 68.53126985, 66.8347374 , ..., 67.68748165,
        52.50864585, 51.72970506],
       [45.36970655, 25.79788881, 33.27246654, ..., 23.72543972,
        53.80399982,  6.02587061],
       ...,
       [10.49537306, 19.59768936, 66.11051069, ..., 12.61463577,
         3.60315712, 41.67107652],
       [23.90471164, 31.58587918, 39.84477097, ..., 26.81812776,
        72.30823558, 77.98442878],
       [27.97290689, 71.45867571, 48.48381403, ..., 30.46547166,
        14.80703184, 57.19274033]])

In [7]:
intensity_matrix = ca.get_intensity_matrix(n_states, mu, sigma, model_type=model_type)
phi_0 = ca._get_initial_state(n_states, start_width,model_type=model_type, prior_type="Centered")
intensity_matrix, phi_0

(Array([[[[-2. ,  0.5,  0. , ...,  0. ,  0. ,  0. ],
          [ 2. , -2. ,  0.5, ...,  0. ,  0. ,  0. ],
          [ 0. ,  1.5, -2. , ...,  0. ,  0. ,  0. ],
          ...,
          [ 0. ,  0. ,  0. , ..., -2. ,  0.5,  0. ],
          [ 0. ,  0. ,  0. , ...,  1.5, -2. ,  2. ],
          [ 0. ,  0. ,  0. , ...,  0. ,  1.5, -2. ]]]], dtype=float64),
 Array([[[[0.        ],
          [0.        ],
          [0.        ],
          [0.        ],
          [0.        ],
          [0.        ],
          [0.        ],
          [0.        ],
          [0.        ],
          [0.        ],
          [0.        ],
          [0.        ],
          [0.        ],
          [0.        ],
          [0.        ],
          [0.        ],
          [0.        ],
          [0.        ],
          [0.        ],
          [0.        ],
          [0.        ],
          [0.        ],
          [0.        ],
          [0.        ],
          [0.        ],
          [0.        ],
          [0.        ],


In [8]:
Mc, Mw, Mn = ca._get_measurement_matrix(n_states, threshold, prob=measurement_prob, model_type = model_type)
Mc

Array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 1.]], dtype=float64)

In [9]:
t = t_s #np.asarray([[4.5]]) #
phi_t = ca.perform_state_transition(intensity_matrix=intensity_matrix, RT_s=t, RA_s = None, delta=delta, 
Mc = Mc, Mn = Mn, Mw = Mw, phi_0=phi_0, 
transition_type=transition_type, likelihood_type="SINGLE")
phi_t.shape

(20, 400, 101, 1)

In [10]:
phi_t

Array([[[[3.48476707e-28],
         [2.09500891e-27],
         [1.10465363e-26],
         ...,
         [6.73699507e-06],
         [4.89629589e-06],
         [2.38854094e-06]],

        [[4.20898009e-66],
         [8.24973217e-65],
         [1.42989366e-63],
         ...,
         [5.33145874e-43],
         [9.26673211e-44],
         [1.39950556e-44]],

        [[1.76598628e-25],
         [6.52272550e-25],
         [1.70028885e-24],
         ...,
         [1.45032662e-01],
         [4.23311203e-01],
         [3.16170315e-01]],

        ...,

        [[4.41855554e-25],
         [1.65578078e-24],
         [4.42890993e-24],
         ...,
         [1.38720772e-01],
         [3.90145564e-01],
         [2.89735717e-01]],

        [[2.06791688e-26],
         [7.49490719e-26],
         [1.88749112e-25],
         ...,
         [1.47872107e-01],
         [4.41923191e-01],
         [3.31251585e-01]],

        [[4.65853160e-25],
         [2.07065535e-24],
         [7.28829495e-24],
         ...,
 

In [11]:
phi_t.sum(axis=-2, keepdims=True).sum()

Array(8000., dtype=float64)

In [12]:
[phi_i_j.squeeze().sum() for phi_i in phi_t for phi_i_j in phi_i ]

[Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 Array(1., dtype=float64),
 

In [13]:
phi_t[0,0,:,0]

Array([3.48476707e-28, 2.09500891e-27, 1.10465363e-26, 5.83067696e-26,
       3.02621286e-25, 1.54125912e-24, 7.69918406e-24, 3.77111453e-23,
       1.81058107e-22, 8.51833549e-22, 3.92593163e-21, 1.77191168e-20,
       7.82907282e-20, 3.38534245e-19, 1.43209421e-18, 5.92471805e-18,
       2.39628879e-17, 9.47179423e-17, 3.65755989e-16, 1.37930280e-15,
       5.07783220e-15, 1.82426616e-14, 6.39335913e-14, 2.18494594e-13,
       7.27885111e-13, 2.36284946e-12, 7.47140261e-12, 2.30040740e-11,
       6.89429908e-11, 2.01051699e-10, 5.70310361e-10, 1.57311060e-09,
       4.21809374e-09, 1.09914133e-08, 2.78259799e-08, 6.84219174e-08,
       1.63375208e-07, 3.78732580e-07, 8.52229399e-07, 1.86119896e-06,
       3.94449209e-06, 8.11178442e-06, 1.61863967e-05, 3.13394361e-05,
       5.88784277e-05, 1.07344748e-04, 1.89941447e-04, 3.26247651e-04,
       5.44073897e-04, 8.81180973e-04, 1.38644429e-03, 2.11993316e-03,
       3.15133701e-03, 4.55625463e-03, 6.41009675e-03, 8.77973059e-03,
      

stats.multinomial(n=1, p=phi_t[0,0,:,0]).rvs()

In [14]:
phi_t

Array([[[[3.48476707e-28],
         [2.09500891e-27],
         [1.10465363e-26],
         ...,
         [6.73699507e-06],
         [4.89629589e-06],
         [2.38854094e-06]],

        [[4.20898009e-66],
         [8.24973217e-65],
         [1.42989366e-63],
         ...,
         [5.33145874e-43],
         [9.26673211e-44],
         [1.39950556e-44]],

        [[1.76598628e-25],
         [6.52272550e-25],
         [1.70028885e-24],
         ...,
         [1.45032662e-01],
         [4.23311203e-01],
         [3.16170315e-01]],

        ...,

        [[4.41855554e-25],
         [1.65578078e-24],
         [4.42890993e-24],
         ...,
         [1.38720772e-01],
         [3.90145564e-01],
         [2.89735717e-01]],

        [[2.06791688e-26],
         [7.49490719e-26],
         [1.88749112e-25],
         ...,
         [1.47872107e-01],
         [4.41923191e-01],
         [3.31251585e-01]],

        [[4.65853160e-25],
         [2.07065535e-24],
         [7.28829495e-24],
         ...,
 

def test(a,d):
    print(a.shape)
    return a

np.apply_over_axes(test, phi_t, axes=[0]).shape
#np.apply_along_axis(test, -2, phi_t).shape

In [15]:
import jax
rng = jax.random.key(1)
rng

Array((), dtype=key<fry>) overlaying:
[0 1]

In [16]:
states_t = dist.Multinomial(total_count=1, probs=phi_t[...,0]).sample(key=(rng:=jax.random.split(rng)[0]))
states_t.shape

(20, 400, 101)

[stats.multinomial(n=1, p=phi_i_j.squeeze()).rvs() for phi_i in phi_t for phi_i_j in phi_i ]

states_t1 = np.array([stats.multinomial(n=1, p=phi_i_j.squeeze()).rvs() for phi_i in phi_t for phi_i_j in phi_i ])
states_t1.shape

In [17]:
np.argwhere(states_t)

array([[  0,   0,  67],
       [  0,   1,  54],
       [  0,   2,  82],
       ...,
       [ 19, 397,  82],
       [ 19, 398,  72],
       [ 19, 399,  99]])

In [18]:
np.argwhere(states_t).T

array([[  0,   0,   0, ...,  19,  19,  19],
       [  0,   1,   2, ..., 397, 398, 399],
       [ 67,  54,  82, ...,  82,  72,  99]])

In [19]:
state_final = np.argwhere(states_t)
state_final

array([[  0,   0,  67],
       [  0,   1,  54],
       [  0,   2,  82],
       ...,
       [ 19, 397,  82],
       [ 19, 398,  72],
       [ 19, 399,  99]])

In [20]:
n_states - threshold

100

In [21]:
t_s.shape

(20, 400)

In [22]:
state_final >= n_states - threshold - 1

array([[False, False, False],
       [False, False, False],
       [False, False, False],
       ...,
       [False,  True, False],
       [False,  True, False],
       [False,  True,  True]])

np.where((state_final < threshold - 1) | (state_final >= n_states - threshold - 1))

In [23]:
RA = np.select([
    state_final[:,[-1]] < threshold - 1,
    state_final[:,[-1]] >= n_states - threshold - 1
], [0,1], default = np.nan)#[:,-1]
RA.shape

(8000, 1)

In [24]:
t_s.flatten()[:,None].shape

(8000, 1)

In [25]:
state_final.shape

(8000, 3)

In [26]:
(t_s.flatten()[:,None]).shape

(8000, 1)

In [27]:
Response = np.hstack((state_final, RA, t_s.flatten()[:,None]*delta))
Response

array([[  0.        ,   0.        ,  67.        ,          nan,
          9.13290222],
       [  0.        ,   1.        ,  54.        ,          nan,
          0.56167502],
       [  0.        ,   2.        ,  82.        ,          nan,
         33.60781787],
       ...,
       [ 19.        , 397.        ,  82.        ,          nan,
         15.23273583],
       [ 19.        , 398.        ,  72.        ,          nan,
          7.40351592],
       [ 19.        , 399.        ,  99.        ,   1.        ,
         28.59637016]])

In [28]:
df_res = pd.DataFrame(Response, columns=["I", "J", "state", "RA", "RT"])
df_res

,I,J,state,RA,RT
0,0.0,0.0,67.0,NaN,9.132902
1,0.0,1.0,54.0,NaN,0.561675
2,0.0,2.0,82.0,NaN,33.607818
3,0.0,3.0,85.0,NaN,23.500515
4,0.0,4.0,100.0,1.0,25.099545
...,...,...,...,...,...
7995,19.0,395.0,99.0,1.0,38.474195
7996,19.0,396.0,48.0,NaN,1.078763
7997,19.0,397.0,82.0,NaN,15.232736
7998,19.0,398.0,72.0,NaN,7.403516


In [29]:
df_res.dropna().groupby(["I"]).count()

,J,state,RA,RT
I,,,,
0.0,122,122,122,122
1.0,145,145,145,145
2.0,126,126,126,126
3.0,125,125,125,125
4.0,141,141,141,141
5.0,134,134,134,134
6.0,143,143,143,143
7.0,113,113,113,113
8.0,131,131,131,131


In [30]:
df_res = df_res.dropna()
get_id = (df_res.groupby(["I"]).count() < J)[["J"]].query("J == True").index.values
get_id

array([], dtype=float64)

In [36]:
df_sample = df_res.groupby(["I"]).nth(slice(None, J)).drop("J", axis=1)
df_sample

,I,state,RA,RT
4,0.0,100.0,1.0,25.099545
8,0.0,100.0,1.0,29.210640
11,0.0,100.0,1.0,38.810567
13,0.0,99.0,1.0,27.287228
19,0.0,99.0,1.0,23.331122
...,...,...,...,...
7923,19.0,100.0,1.0,29.869043
7930,19.0,99.0,1.0,39.757442
7936,19.0,100.0,1.0,26.893303
7942,19.0,100.0,1.0,35.292134


In [37]:
df_sample.groupby(["I"]).count()

,state,RA,RT
I,,,
0.0,100,100,100
1.0,100,100,100
2.0,100,100,100
3.0,100,100,100
4.0,100,100,100
5.0,100,100,100
6.0,100,100,100
7.0,100,100,100
8.0,100,100,100
