In [1]:
import cme.simulators.diffusion_random_walk as drw
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import scipy.stats as stats
import numpy.linalg as ln
import numpy as np
import cme.decision_models.confidence_accumulation as ca
import cme.decision_models.quantum_discrete as qd
import cme.decision_models.diffusion_discrete as dd
import matplotlib.animation as animation
from IPython.display import HTML

In [2]:
n_states_q, start_width, response_width = 5, None, 2
start_width = (n_states_q-2*response_width)
mv = np.arange(-(n_states_q//2), (n_states_q//2)+1)

In [3]:
m_Mc, m_Mw, m_Mn = ca._get_measurement_matrix(n_states_q, 1, prob=0.5, model_type = "Markov")


In [4]:
intensity_matrix_markov = dd._buildK(n_states_q, np.asarray([[1]]), np.asarray([[2]]), transition_type = "TIMESTEP")
intensity_matrix_markov

Array([[[[ 0. ,  0.5,  0. ,  0. ,  0. ],
         [ 0. , -2. ,  0.5,  0. ,  0. ],
         [ 0. ,  1.5, -2. ,  0.5,  0. ],
         [ 0. ,  0. ,  1.5, -2. ,  0. ],
         [ 0. ,  0. ,  0. ,  1.5,  0. ]]]], dtype=float64)

In [5]:
phi_0_markov = ca._get_initial_state(n_states_q, start_width, response_width, model_type="Markov" , prior_type="Centered")
phi_0_markov

Array([[[[0.],
         [0.],
         [1.],
         [0.],
         [0.]]]], dtype=float64)

In [6]:
ca.perform_state_transition(intensity_matrix_markov, np.asarray([[2]]), np.asarray([[1]]), 
                                            m_Mc, m_Mw, m_Mn, phi_0_markov, 0.1, 
                                            transition_type="RT", likelihood_type="SINGLE")

Array([[[[0.07212193],
         [0.04298005],
         [0.10686051],
         [0.12894014],
         [0.64909737]]]], dtype=float64)

In [ ]:
import scipy.linalg as ln

In [ ]:
ln.expm(np.asarray(intensity_matrix_markov)*1) @ phi_0_markov