In [2]:
import numpy as np
import pandas as pd

In [18]:
def _liklihood(x, r):
  a, v, t = x

  print(x)
  r=r-t
  r = r+0.01

  f1 = a / np.sqrt(2 * np.pi * (r)**3 )
  f2 = ((a - v*(r))**2) / 2*(r)
  
  likl = f1 * np.exp(-f2)
  
  likl = np.where(np.isinf(likl), 0, likl)

  likl = np.log(likl.sum())

  likl = np.where(np.isinf(likl), 0, likl)
  likl = np.where(np.isnan(likl), 0, likl)

  return likl

In [15]:
_liklihood((1,0,1),1)

(1, 0, 1)


/tmp/ipykernel_3366/1458598981.py:7: RuntimeWarning: divide by zero encountered in scalar divide
  f1 = a / np.sqrt(2 * np.pi * (r)**3 )
/tmp/ipykernel_3366/1458598981.py:13: RuntimeWarning: divide by zero encountered in log
  likl = np.log(likl.sum())


array(0.)

In [16]:
_liklihood((0.1,2,0.05),1)

(0.1, 2, 0.05)


array(-4.68358368)

In [5]:
df = pd.read_csv("data/ES_Neu_Trials.csv").drop("Unnamed: 0", axis=1)
item_count = df.groupby("subjID").count().iloc[0,1]
df = df.assign(item_id = np.tile(np.arange(0,item_count), 258)) 

r = (df.drop("choice", axis=1)
    .pivot(columns="item_id",index="subjID", values="RT")
    .reset_index().drop(columns="subjID").to_numpy())
r

array([[1.0011, 1.0531, 0.5532, ..., 0.7582, 0.7302, 0.5642],
       [0.7622, 0.6182, 0.6292, ..., 0.7622, 0.5012, 0.8291],
       [0.9761, 1.2901, 0.8821, ..., 0.7272, 0.7692, 0.5502],
       ...,
       [0.4922, 0.7112, 0.6682, ..., 0.6882, 0.5672, 0.7672],
       [0.8243, 0.7003, 1.3922, ..., 1.1593, 0.8403, 0.9343],
       [0.7033, 0.6173, 0.6413, ..., 0.7503, 0.6474, 0.6374]])

In [20]:
import scipy.optimize as opt

opt.minimize(_liklihood, x0 = [0.1, 2, 0.05], args = r, method="BFGS")

[0.1  2.   0.05]
[0.10000001 2.         0.05      ]
[0.1        2.00000001 0.05      ]
[0.1        2.         0.05000001]


/tmp/ipykernel_3366/2840236154.py:8: RuntimeWarning: invalid value encountered in sqrt
  f1 = a / np.sqrt(2 * np.pi * (r)**3 )


  message: Optimization terminated successfully.
  success: True
   status: 0
      fun: 0.0
        x: [ 1.000e-01  2.000e+00  5.000e-02]
      nit: 0
      jac: [ 0.000e+00  0.000e+00  0.000e+00]
 hess_inv: [[1 0 0]
            [0 1 0]
            [0 0 1]]
     nfev: 4
     njev: 1